[package]
name = "noted"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
ron = "0.8.1"
keyring = "2.3.2"
dirs = "5.0.1"

[dependencies.iced]
version = "0.12.1"
features = ["image"]